# version: '3.7'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8080:8080
#       - 80:8080
#       - 8080:80
#       # - 80:3000
#     depends_on:
#       mysqldb:
#         condition: service_healthy
#     environment:
#       # - DB_HOST=mysqldb
#       - DB_HOST=127.0.0.1
#       - DB_PORT=3306
#       - DB_NAME=node_mysql
#       - DB_USERNAME=root
#       - DB_PASSWORD=root
#     networks:
#       - nodejs-mysql-network

#   mysqldb:
#     image: mysql:8.0.33
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_DATABASE=node_mysql
#       - MYSQL_ROOT_PASSWORD=
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - nodejs-mysql-network
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       retries: 10
#       interval: 3s
#       timeout: 30s
# volumes:
#   mysql-data:
# networks:
#   nodejs-mysql-network:
#     name: nodejs-mysql-network

# from : https://github.com/bervProject/node-back4app-example/blob/main/docker-compose.yml
# docker-compose for local development only
# services:
#   mysql:
#     image: mysql:8.2-oracle
#     container_name: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     networks:
#       - backend
#     # uncomment ports if you wish to expose to another app
#     # ports:
#       # - 3306:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: developmentPass
#       MYSQL_DATABASE: app
#   myservice:
#     image: myservice:latest
#     restart: always
#     networks:
#       - backend
#     depends_on:
#       - mysql
#     build:
#       context: .
#     ports:
#       - 5000:5000
#     environment:
#       CONNECTION_STRING: mysql://root:developmentPass@mysql:3306/app

# networks:
#   backend:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 80:80
      # - 8080:80
      # - 80:8080
      # - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # - DB_HOST=mysqldb
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_NAME=node_mysql
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - nodejs-mysql-network
      
    # 
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-data:/var/lib/mysql'
            # - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - nodejs-mysql-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p root"]
            retries: 3
            timeout: 5s
